### ISSUE TITLE
redirect_to wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by benjaminwols** [harvard-dce/dce_lti#7]
My format.html {redirect_to path, notice: "notice" } results in an error: redirect_to wrong number of arguments (2 for 1)

I fixed it by adding response_status = {} to redirect_to_helper.rb, but don't know if this is the correct way.

New code:
module DceLti
  module RedirectToHelper
    def redirect_to(options, response_status = {})

**Comment by djcp** [comment]
What version of Rails are you using? Is your code on github, or somewhere else visible?

**Comment by djcp** [comment]
Ahh, I see. We need to pass through response status to `super()`. I'll release a bugfix, give me a few minutes.

**Comment by djcp** [comment]
But to be clear - the second argument is for the status code, I'm not sure exactly what you're doing but it might look something like:

```
redirect_to(notice_path(notice: 'notice'))
```

**Comment by djcp** [comment]
Can you try [this](https://github.com/harvard-dce/dce_lti/tree/djcp-fix-redirect_to_helper) branch?

```
# In your Gemfile. . .
gem :dce_lti, git: 'https://github.com/harvard-dce/dce_lti', branch: 'djcp-fix-redirect_to_helper'
```

I'll release 0.5.3 once I hear back from you (or even if I don't)

**Comment by benjaminwols** [comment]
This is what I was trying to do. (Default rails 4.2 scaffold generated)
if @setting.save
        format.html { @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
end

The redirect_to_helper did not accept the notice option, but now it is working.
Thanks.

**Comment by djcp** [comment]
Great! I'll release 0.5.3 with this fix today.
