### ISSUE TITLE
ActiveRecord::StatementInvalid in DceLti::SessionsController#create

### ISSUE THREAD

**Issue by benjaminwols** [harvard-dce/dce_lti#9]
I get this error random. Sometimes session#create works without an error.

I think it has something to do with this row in app/services/dce_lti/user_initializer.rb:14:in `find_from':
User.find_or_create_by(lti_user_id: tool_provider.user_id).tap do |user|

I have a table named users and when the error occurs the query is as follows:
User Load (3.1ms)  SELECT  "users".* FROM "users" WHERE "users"."lti_user_id" = '097c051abd8484048f387641b1834c07' LIMIT 1
SQLite3::SQLException: no such column: users.lti_user_id: SELECT  "users".* FROM "users" WHERE "users"."lti_user_id" = '097c051abd8484048f387641b1834c07' LIMIT 1

But when the error not occurs, the query looks like this:
DceLti::User Load (0.2ms)  SELECT  "dce_lti_users".* FROM "dce_lti_users" WHERE "dce_lti_users"."lti_user_id" = ? LIMIT 1  [["lti_user_id", "097c051abd8484048f387641b1834c07"]]

So the wrong table is selected sometimes and I can't figure out way. It occured today for the first time.

![screen shot 2015-05-27 at 19 33 40](https://cloud.githubusercontent.com/assets/12526288/7843080/a205df2c-04a7-11e5-92c6-701f1d786224.png)
![screen shot 2015-05-27 at 19 33 56](https://cloud.githubusercontent.com/assets/12526288/7843081/a207c63e-04a7-11e5-9365-5db3f6e3619b.png)

**Comment by djcp** [comment]
This gem creates your user model for you, and the model is named `DceLti::User`. Rails would introspect the ID column for that model to be `dce_lti_user_id` and the table to be `dce_lti_users`.

Remember that DceLti::UserInitializer is namespaced in the DceLti module, so all subsequent class references are relative to that module.

Also, this gem isn't tested under sqlite3 and I don't think it's worth supporting.
